/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as AuthRouteImport } from './routes/auth';
import { Route as IndexRouteImport } from './routes/index';
import { Route as SupportIndexRouteImport } from './routes/support.index';
import { Route as ProfileIndexRouteImport } from './routes/profile.index';
import { Route as KnowledgeBaseIndexRouteImport } from './routes/knowledge-base.index';
import { Route as IssuesIndexRouteImport } from './routes/issues.index';
import { Route as HistoryIndexRouteImport } from './routes/history.index';
import { Route as HandrulesIndexRouteImport } from './routes/handrules.index';
import { Route as SupportChatIdRouteImport } from './routes/support.$chatId';
import { Route as KnowledgeBaseSlugRouteImport } from './routes/knowledge-base.$slug';
import { Route as IssuesTopicRouteImport } from './routes/issues.$topic';
import { Route as HistoryChatIdRouteImport } from './routes/history.$chatId';
import { Route as KnowledgeBaseSlugIndexRouteImport } from './routes/knowledge-base.$slug.index';
import { Route as IssuesTopicIndexRouteImport } from './routes/issues.$topic.index';
import { Route as KnowledgeBaseSlugSectionIdRouteImport } from './routes/knowledge-base.$slug.$sectionId';
import { Route as IssuesTopicChatIdRouteImport } from './routes/issues.$topic.$chatId';

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any);
const KnowledgeBaseIndexRoute = KnowledgeBaseIndexRouteImport.update({
  id: '/knowledge-base/',
  path: '/knowledge-base/',
  getParentRoute: () => rootRouteImport,
} as any);
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any);
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any);
const HandrulesIndexRoute = HandrulesIndexRouteImport.update({
  id: '/handrules/',
  path: '/handrules/',
  getParentRoute: () => rootRouteImport,
} as any);
const SupportChatIdRoute = SupportChatIdRouteImport.update({
  id: '/support/$chatId',
  path: '/support/$chatId',
  getParentRoute: () => rootRouteImport,
} as any);
const KnowledgeBaseSlugRoute = KnowledgeBaseSlugRouteImport.update({
  id: '/knowledge-base/$slug',
  path: '/knowledge-base/$slug',
  getParentRoute: () => rootRouteImport,
} as any);
const IssuesTopicRoute = IssuesTopicRouteImport.update({
  id: '/issues/$topic',
  path: '/issues/$topic',
  getParentRoute: () => rootRouteImport,
} as any);
const HistoryChatIdRoute = HistoryChatIdRouteImport.update({
  id: '/history/$chatId',
  path: '/history/$chatId',
  getParentRoute: () => rootRouteImport,
} as any);
const KnowledgeBaseSlugIndexRoute = KnowledgeBaseSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeBaseSlugRoute,
} as any);
const IssuesTopicIndexRoute = IssuesTopicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IssuesTopicRoute,
} as any);
const KnowledgeBaseSlugSectionIdRoute =
  KnowledgeBaseSlugSectionIdRouteImport.update({
    id: '/$sectionId',
    path: '/$sectionId',
    getParentRoute: () => KnowledgeBaseSlugRoute,
  } as any);
const IssuesTopicChatIdRoute = IssuesTopicChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => IssuesTopicRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/auth': typeof AuthRoute;
  '/register': typeof RegisterRoute;
  '/history/$chatId': typeof HistoryChatIdRoute;
  '/issues/$topic': typeof IssuesTopicRouteWithChildren;
  '/knowledge-base/$slug': typeof KnowledgeBaseSlugRouteWithChildren;
  '/support/$chatId': typeof SupportChatIdRoute;
  '/handrules': typeof HandrulesIndexRoute;
  '/history': typeof HistoryIndexRoute;
  '/issues': typeof IssuesIndexRoute;
  '/knowledge-base': typeof KnowledgeBaseIndexRoute;
  '/profile': typeof ProfileIndexRoute;
  '/support': typeof SupportIndexRoute;
  '/issues/$topic/$chatId': typeof IssuesTopicChatIdRoute;
  '/knowledge-base/$slug/$sectionId': typeof KnowledgeBaseSlugSectionIdRoute;
  '/issues/$topic/': typeof IssuesTopicIndexRoute;
  '/knowledge-base/$slug/': typeof KnowledgeBaseSlugIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/auth': typeof AuthRoute;
  '/register': typeof RegisterRoute;
  '/history/$chatId': typeof HistoryChatIdRoute;
  '/support/$chatId': typeof SupportChatIdRoute;
  '/handrules': typeof HandrulesIndexRoute;
  '/history': typeof HistoryIndexRoute;
  '/issues': typeof IssuesIndexRoute;
  '/knowledge-base': typeof KnowledgeBaseIndexRoute;
  '/profile': typeof ProfileIndexRoute;
  '/support': typeof SupportIndexRoute;
  '/issues/$topic/$chatId': typeof IssuesTopicChatIdRoute;
  '/knowledge-base/$slug/$sectionId': typeof KnowledgeBaseSlugSectionIdRoute;
  '/issues/$topic': typeof IssuesTopicIndexRoute;
  '/knowledge-base/$slug': typeof KnowledgeBaseSlugIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/auth': typeof AuthRoute;
  '/register': typeof RegisterRoute;
  '/history/$chatId': typeof HistoryChatIdRoute;
  '/issues/$topic': typeof IssuesTopicRouteWithChildren;
  '/knowledge-base/$slug': typeof KnowledgeBaseSlugRouteWithChildren;
  '/support/$chatId': typeof SupportChatIdRoute;
  '/handrules/': typeof HandrulesIndexRoute;
  '/history/': typeof HistoryIndexRoute;
  '/issues/': typeof IssuesIndexRoute;
  '/knowledge-base/': typeof KnowledgeBaseIndexRoute;
  '/profile/': typeof ProfileIndexRoute;
  '/support/': typeof SupportIndexRoute;
  '/issues/$topic/$chatId': typeof IssuesTopicChatIdRoute;
  '/knowledge-base/$slug/$sectionId': typeof KnowledgeBaseSlugSectionIdRoute;
  '/issues/$topic/': typeof IssuesTopicIndexRoute;
  '/knowledge-base/$slug/': typeof KnowledgeBaseSlugIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/auth'
    | '/register'
    | '/history/$chatId'
    | '/issues/$topic'
    | '/knowledge-base/$slug'
    | '/support/$chatId'
    | '/handrules'
    | '/history'
    | '/issues'
    | '/knowledge-base'
    | '/profile'
    | '/support'
    | '/issues/$topic/$chatId'
    | '/knowledge-base/$slug/$sectionId'
    | '/issues/$topic/'
    | '/knowledge-base/$slug/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/auth'
    | '/register'
    | '/history/$chatId'
    | '/support/$chatId'
    | '/handrules'
    | '/history'
    | '/issues'
    | '/knowledge-base'
    | '/profile'
    | '/support'
    | '/issues/$topic/$chatId'
    | '/knowledge-base/$slug/$sectionId'
    | '/issues/$topic'
    | '/knowledge-base/$slug';
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/register'
    | '/history/$chatId'
    | '/issues/$topic'
    | '/knowledge-base/$slug'
    | '/support/$chatId'
    | '/handrules/'
    | '/history/'
    | '/issues/'
    | '/knowledge-base/'
    | '/profile/'
    | '/support/'
    | '/issues/$topic/$chatId'
    | '/knowledge-base/$slug/$sectionId'
    | '/issues/$topic/'
    | '/knowledge-base/$slug/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRoute;
  RegisterRoute: typeof RegisterRoute;
  HistoryChatIdRoute: typeof HistoryChatIdRoute;
  IssuesTopicRoute: typeof IssuesTopicRouteWithChildren;
  KnowledgeBaseSlugRoute: typeof KnowledgeBaseSlugRouteWithChildren;
  SupportChatIdRoute: typeof SupportChatIdRoute;
  HandrulesIndexRoute: typeof HandrulesIndexRoute;
  HistoryIndexRoute: typeof HistoryIndexRoute;
  IssuesIndexRoute: typeof IssuesIndexRoute;
  KnowledgeBaseIndexRoute: typeof KnowledgeBaseIndexRoute;
  ProfileIndexRoute: typeof ProfileIndexRoute;
  SupportIndexRoute: typeof SupportIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auth': {
      id: '/auth';
      path: '/auth';
      fullPath: '/auth';
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/support/': {
      id: '/support/';
      path: '/support';
      fullPath: '/support';
      preLoaderRoute: typeof SupportIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/profile/': {
      id: '/profile/';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof ProfileIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/knowledge-base/': {
      id: '/knowledge-base/';
      path: '/knowledge-base';
      fullPath: '/knowledge-base';
      preLoaderRoute: typeof KnowledgeBaseIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/issues/': {
      id: '/issues/';
      path: '/issues';
      fullPath: '/issues';
      preLoaderRoute: typeof IssuesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/history/': {
      id: '/history/';
      path: '/history';
      fullPath: '/history';
      preLoaderRoute: typeof HistoryIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/handrules/': {
      id: '/handrules/';
      path: '/handrules';
      fullPath: '/handrules';
      preLoaderRoute: typeof HandrulesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/support/$chatId': {
      id: '/support/$chatId';
      path: '/support/$chatId';
      fullPath: '/support/$chatId';
      preLoaderRoute: typeof SupportChatIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/knowledge-base/$slug': {
      id: '/knowledge-base/$slug';
      path: '/knowledge-base/$slug';
      fullPath: '/knowledge-base/$slug';
      preLoaderRoute: typeof KnowledgeBaseSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/issues/$topic': {
      id: '/issues/$topic';
      path: '/issues/$topic';
      fullPath: '/issues/$topic';
      preLoaderRoute: typeof IssuesTopicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/history/$chatId': {
      id: '/history/$chatId';
      path: '/history/$chatId';
      fullPath: '/history/$chatId';
      preLoaderRoute: typeof HistoryChatIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/knowledge-base/$slug/': {
      id: '/knowledge-base/$slug/';
      path: '/';
      fullPath: '/knowledge-base/$slug/';
      preLoaderRoute: typeof KnowledgeBaseSlugIndexRouteImport;
      parentRoute: typeof KnowledgeBaseSlugRoute;
    };
    '/issues/$topic/': {
      id: '/issues/$topic/';
      path: '/';
      fullPath: '/issues/$topic/';
      preLoaderRoute: typeof IssuesTopicIndexRouteImport;
      parentRoute: typeof IssuesTopicRoute;
    };
    '/knowledge-base/$slug/$sectionId': {
      id: '/knowledge-base/$slug/$sectionId';
      path: '/$sectionId';
      fullPath: '/knowledge-base/$slug/$sectionId';
      preLoaderRoute: typeof KnowledgeBaseSlugSectionIdRouteImport;
      parentRoute: typeof KnowledgeBaseSlugRoute;
    };
    '/issues/$topic/$chatId': {
      id: '/issues/$topic/$chatId';
      path: '/$chatId';
      fullPath: '/issues/$topic/$chatId';
      preLoaderRoute: typeof IssuesTopicChatIdRouteImport;
      parentRoute: typeof IssuesTopicRoute;
    };
  }
}

interface IssuesTopicRouteChildren {
  IssuesTopicChatIdRoute: typeof IssuesTopicChatIdRoute;
  IssuesTopicIndexRoute: typeof IssuesTopicIndexRoute;
}

const IssuesTopicRouteChildren: IssuesTopicRouteChildren = {
  IssuesTopicChatIdRoute: IssuesTopicChatIdRoute,
  IssuesTopicIndexRoute: IssuesTopicIndexRoute,
};

const IssuesTopicRouteWithChildren = IssuesTopicRoute._addFileChildren(
  IssuesTopicRouteChildren,
);

interface KnowledgeBaseSlugRouteChildren {
  KnowledgeBaseSlugSectionIdRoute: typeof KnowledgeBaseSlugSectionIdRoute;
  KnowledgeBaseSlugIndexRoute: typeof KnowledgeBaseSlugIndexRoute;
}

const KnowledgeBaseSlugRouteChildren: KnowledgeBaseSlugRouteChildren = {
  KnowledgeBaseSlugSectionIdRoute: KnowledgeBaseSlugSectionIdRoute,
  KnowledgeBaseSlugIndexRoute: KnowledgeBaseSlugIndexRoute,
};

const KnowledgeBaseSlugRouteWithChildren =
  KnowledgeBaseSlugRoute._addFileChildren(KnowledgeBaseSlugRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  RegisterRoute: RegisterRoute,
  HistoryChatIdRoute: HistoryChatIdRoute,
  IssuesTopicRoute: IssuesTopicRouteWithChildren,
  KnowledgeBaseSlugRoute: KnowledgeBaseSlugRouteWithChildren,
  SupportChatIdRoute: SupportChatIdRoute,
  HandrulesIndexRoute: HandrulesIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  KnowledgeBaseIndexRoute: KnowledgeBaseIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
