/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthRouteImport } from './routes/auth';
import { Route as IndexRouteImport } from './routes/index';
import { Route as SupportIndexRouteImport } from './routes/support.index';
import { Route as SupportChatIdRouteImport } from './routes/support.$chatId';

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any);
const SupportChatIdRoute = SupportChatIdRouteImport.update({
  id: '/support/$chatId',
  path: '/support/$chatId',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/auth': typeof AuthRoute;
  '/support/$chatId': typeof SupportChatIdRoute;
  '/support': typeof SupportIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/auth': typeof AuthRoute;
  '/support/$chatId': typeof SupportChatIdRoute;
  '/support': typeof SupportIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/auth': typeof AuthRoute;
  '/support/$chatId': typeof SupportChatIdRoute;
  '/support/': typeof SupportIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/auth' | '/support/$chatId' | '/support';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/auth' | '/support/$chatId' | '/support';
  id: '__root__' | '/' | '/auth' | '/support/$chatId' | '/support/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRoute;
  SupportChatIdRoute: typeof SupportChatIdRoute;
  SupportIndexRoute: typeof SupportIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth';
      path: '/auth';
      fullPath: '/auth';
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/support/': {
      id: '/support/';
      path: '/support';
      fullPath: '/support';
      preLoaderRoute: typeof SupportIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/support/$chatId': {
      id: '/support/$chatId';
      path: '/support/$chatId';
      fullPath: '/support/$chatId';
      preLoaderRoute: typeof SupportChatIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SupportChatIdRoute: SupportChatIdRoute,
  SupportIndexRoute: SupportIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
