/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Return a simple `pong` response to check the service (and DB connection) is alive.
         */
        get: operations["ping_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Profile
         * @description Возвращает профиль текущего пользователя.
         *     По умолчанию роль определяется из учётной записи пользователя (поставщик/заказчик),
         *     либо может быть явно переопределена параметром role.
         */
        get: operations["get_my_profile_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sample Profile
         * @description Демонстрационный профиль без авторизации.
         *     Демонстрирует цепочку: Компания -> Закупка -> Предложения -> Контракт -> Документы.
         */
        get: operations["get_sample_profile_profile_sample_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User Role
         * @description Переключение роли пользователя между Поставщиком (seller) и Заказчиком (buyer).
         */
        patch: operations["update_user_role_profile_role_patch"];
        trace?: never;
    };
    "/profile/procurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create New Procurement
         * @description [Заказчик] Создать новую закупку.
         *     Компания заказчика публикует закупку с начальной ценой и документацией.
         */
        post: operations["create_new_procurement_profile_procurements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create New Offer
         * @description [Поставщик] Подать предложение на участие в закупке.
         *     Поставщик предлагает свою цену и условия исполнения.
         */
        post: operations["create_new_offer_profile_offers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/procurements/{procurement_id}/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Offer For Procurement
         * @description [Поставщик] Подать предложение на конкретную закупку.
         */
        post: operations["create_offer_for_procurement_profile_procurements__procurement_id__offers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create New Contract
         * @description [Заказчик] Сформировать контракт из выбранного предложения победителя.
         *     Выбранное предложение переходит в статус победителя, закупка переходит в статус 'Контракт заключён',
         *     и формируется государственный/коммерческий контракт со сторонами и условиями.
         */
        post: operations["create_new_contract_profile_contracts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create New Document
         * @description Загрузить / добавить документ к закупке, предложению, контракту или компании.
         */
        post: operations["create_new_document_profile_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Contract
         * @description Получить детальную информацию о контракте со сторонами, предметом, стоимостью,
         *     статусом, сроком исполнения, ответственным, этапом и документами.
         */
        get: operations["get_contract_profile_contracts__contract_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Support Lines */
        get: operations["list_support_lines_support_lines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chats */
        get: operations["list_chats_chats_get"];
        put?: never;
        /** Create Chat */
        post: operations["create_chat_chats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat */
        get: operations["get_chat_chats__chat_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Messages */
        get: operations["get_messages_chats__chat_id__messages_get"];
        put?: never;
        /** Send Message */
        post: operations["send_message_chats__chat_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Message */
        post: operations["stream_message_chats__chat_id__stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Message */
        post: operations["stream_message_chats__chat_id__message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}/request-operator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Operator */
        post: operations["request_operator_chats__chat_id__request_operator_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close */
        post: operations["close_chats__chat_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chat_id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Rate Chat */
        put: operations["rate_chat_chats__chat_id__rating_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Support Chats */
        get: operations["support_chats_support_chats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/support/chats/{chat_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim */
        post: operations["claim_support_chats__chat_id__claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chats */
        get: operations["chats_admin_chats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ratings */
        get: operations["ratings_admin_ratings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ai-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Health */
        get: operations["ai_health_admin_ai_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml-assets/image/{slug}/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proxy Image */
        get: operations["proxy_image_ml_assets_image__slug___filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml-api/knowledge-base": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список мануалов */
        get: operations["list_manuals_ml_api_knowledge_base_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml-api/knowledge-base/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Структура мануала */
        get: operations["get_manual_structure_ml_api_knowledge_base__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml-api/knowledge-base/{slug}/{section_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Содержимое раздела мануала */
        get: operations["get_manual_section_ml_api_knowledge_base__slug___section_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manul": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Manul
         * @description Return the manul image.
         */
        get: operations["get_manul_manul_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActorOut */
        ActorOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
        };
        /** AdminRatingOut */
        AdminRatingOut: {
            /** Stars */
            stars: number;
            /** Comment */
            comment?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Chat Id */
            chat_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            sender_type: components["schemas"]["SenderType"];
            /** Sender Id */
            sender_id?: string | null;
            /** Sender Name */
            sender_name: string;
            /** Support Line Id */
            support_line_id?: number | null;
            /**
             * Chat Title
             * @default
             */
            chat_title: string;
        };
        /** ChatOut */
        ChatOut: {
            /** Id */
            id: string;
            /**
             * Title
             * @default Новый чат
             */
            title: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            status: components["schemas"]["ChatStatus"];
            recipient: components["schemas"]["RecipientOut"];
            support_line: components["schemas"]["SupportLineOut"] | null;
            operator: components["schemas"]["ActorOut"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Handed Off At */
            handed_off_at: string | null;
            /** Assigned At */
            assigned_at: string | null;
            /** Closed At */
            closed_at: string | null;
            close_reason: components["schemas"]["CloseReason"] | null;
            /** Moderation Reason */
            moderation_reason: string | null;
            /** Topic */
            topic?: string | null;
            /** Subtopic */
            subtopic?: string | null;
            rating?: components["schemas"]["RatingOut"] | null;
        };
        /** ChatPage */
        ChatPage: {
            /** Items */
            items: components["schemas"]["ChatOut"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /**
         * ChatStatus
         * @enum {string}
         */
        ChatStatus: ChatStatus;
        /** CloseIn */
        CloseIn: {
            /**
             * Reason
             * @default resolved
             * @enum {string}
             */
            reason: CloseInReason;
        };
        /**
         * CloseReason
         * @enum {string}
         */
        CloseReason: CloseReason;
        /** CompanyProfileOut */
        CompanyProfileOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Full Name */
            full_name: string;
            /** Inn */
            inn: string;
            /** Kpp */
            kpp: string;
            /** Ogrn */
            ogrn: string;
            /** Address */
            address: string;
            /** Ceo */
            ceo: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            /** Website */
            website?: string | null;
            role: components["schemas"]["Role"];
            /** Role Label */
            role_label: string;
            /** Documents */
            documents?: components["schemas"]["DocumentOut"][];
        };
        /** ContractCreateIn */
        ContractCreateIn: {
            /** Offer Id */
            offer_id: string;
            /** Title */
            title?: string | null;
            /** Subject */
            subject?: string | null;
            /** Execution Period */
            execution_period?: string | null;
            /** Responsible Person */
            responsible_person?: string | null;
            /** Execution Stage */
            execution_stage?: string | null;
            /** Documents */
            documents?: components["schemas"]["DocumentCreateIn"][];
        };
        /** ContractOut */
        ContractOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            parties: components["schemas"]["ContractPartiesOut"];
            /** Subject */
            subject: string;
            /** Price */
            price: number;
            /**
             * Currency
             * @default RUB
             */
            currency: string;
            /** Status */
            status: string;
            /** Execution Period */
            execution_period: string;
            /** Responsible Person */
            responsible_person: string;
            /** Execution Stage */
            execution_stage: string;
            /** Documents */
            documents?: components["schemas"]["DocumentOut"][];
        };
        /** ContractPartiesOut */
        ContractPartiesOut: {
            customer: components["schemas"]["PartyOut"];
            supplier: components["schemas"]["PartyOut"];
        };
        /** DocumentCreateIn */
        DocumentCreateIn: {
            /** Title */
            title: string;
            /**
             * File Type
             * @default application/pdf
             */
            file_type: string;
            /**
             * Size Bytes
             * @default 1024
             */
            size_bytes: number;
            /**
             * Category
             * @default procurement
             * @enum {string}
             */
            category: DocumentCreateInCategory;
            /** Target Id */
            target_id?: string | null;
        };
        /** DocumentOut */
        DocumentOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** File Type */
            file_type: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /**
             * Category
             * @description Категория документа: procurement, contract, offer, company
             */
            category: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /** Login */
            login: string;
            /** Password */
            password: string;
        };
        /** MessageIn */
        MessageIn: {
            /** Text */
            text: string;
            /**
             * Client Message Id
             * Format: uuid
             */
            client_message_id: string;
        };
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: string;
            /** Chat Id */
            chat_id: string;
            /** Sequence */
            sequence: number;
            sender_type: components["schemas"]["SenderType"];
            /** Sender Id */
            sender_id?: string | null;
            /** Sender Name */
            sender_name: string;
            /** Support Line Id */
            support_line_id?: number | null;
            /** Text */
            text: string;
            /** Citations */
            citations?: {
                [key: string]: unknown;
            }[];
            /** Tool Calls */
            tool_calls?: {
                [key: string]: unknown;
            }[];
            /** Reply To Message Id */
            reply_to_message_id?: string | null;
            /**
             * Is Redacted
             * @default false
             */
            is_redacted: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MessagePage */
        MessagePage: {
            /** Items */
            items: components["schemas"]["MessageOut"][];
            /** Next Sequence */
            next_sequence: number;
            /** Has More */
            has_more: boolean;
        };
        /** OfferCreateIn */
        OfferCreateIn: {
            /** Procurement Id */
            procurement_id: string;
            /** Price */
            price: number;
            /** Details */
            details: string;
            /** Documents */
            documents?: components["schemas"]["DocumentCreateIn"][];
        };
        /** OfferOut */
        OfferOut: {
            /** Id */
            id: string;
            /** Procurement Id */
            procurement_id: string;
            /** Procurement Title */
            procurement_title: string;
            /** Supplier Name */
            supplier_name: string;
            /** Supplier Inn */
            supplier_inn: string;
            /** Price */
            price: number;
            /** Status */
            status: string;
            /**
             * Is Winner
             * @default false
             */
            is_winner: boolean;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Details */
            details: string;
            /** Documents */
            documents?: components["schemas"]["DocumentOut"][];
        };
        /** PartyOut */
        PartyOut: {
            /**
             * Role
             * @enum {string}
             */
            role: PartyOutRole;
            /** Role Label */
            role_label: string;
            /** Company Name */
            company_name: string;
            /** Inn */
            inn: string;
            /** Kpp */
            kpp: string;
            /** Representative */
            representative: string;
        };
        /** ProcurementCreateIn */
        ProcurementCreateIn: {
            /** Title */
            title: string;
            /** Initial Price */
            initial_price: number;
            /**
             * Currency
             * @default RUB
             */
            currency: string;
            /** Submission Deadline */
            submission_deadline?: string | null;
            /** Number */
            number?: string | null;
            /** Documents */
            documents?: components["schemas"]["DocumentCreateIn"][];
        };
        /** ProcurementOut */
        ProcurementOut: {
            /** Id */
            id: string;
            /** Number */
            number: string;
            /** Title */
            title: string;
            /** Customer Name */
            customer_name: string;
            /** Customer Inn */
            customer_inn: string;
            /** Initial Price */
            initial_price: number;
            /**
             * Currency
             * @default RUB
             */
            currency: string;
            /** Status */
            status: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /**
             * Submission Deadline
             * Format: date-time
             */
            submission_deadline: string;
            /** Documents */
            documents?: components["schemas"]["DocumentOut"][];
            /**
             * Offers Count
             * @default 0
             */
            offers_count: number;
        };
        /** ProfileViewOut */
        ProfileViewOut: {
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["Role"];
            /** Type Label */
            type_label: string;
            company: components["schemas"]["CompanyProfileOut"];
            /** Procurements */
            procurements: components["schemas"]["ProcurementOut"][];
            /** Offers */
            offers: components["schemas"]["OfferOut"][];
            /** Contracts */
            contracts: components["schemas"]["ContractOut"][];
            /** Documents */
            documents: components["schemas"]["DocumentOut"][];
        };
        /** RatingIn */
        RatingIn: {
            /** Stars */
            stars: number;
            /** Comment */
            comment?: string | null;
        };
        /** RatingOut */
        RatingOut: {
            /** Stars */
            stars: number;
            /** Comment */
            comment?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Chat Id */
            chat_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            sender_type?: components["schemas"]["SenderType"] | null;
            /** Sender Id */
            sender_id?: string | null;
            /** Sender Name */
            sender_name?: string | null;
            /** Support Line Id */
            support_line_id?: number | null;
        };
        /** RatingPage */
        RatingPage: {
            /** Items */
            items: components["schemas"]["AdminRatingOut"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** RecipientOut */
        RecipientOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: RecipientOutKind;
            /** Display Name */
            display_name: string;
            support_line?: components["schemas"]["SupportLineOut"] | null;
            operator?: components["schemas"]["ActorOut"] | null;
        };
        /** RegisterIn */
        RegisterIn: {
            /** Login */
            login: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name?: string | null;
            /** @default buyer */
            role: components["schemas"]["Role"];
            /** Support Line Id */
            support_line_id?: number | null;
        };
        /** RequestOperatorIn */
        RequestOperatorIn: {
            /** Support Line Id */
            support_line_id: number;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: Role;
        /** SendResult */
        SendResult: {
            chat: components["schemas"]["ChatOut"];
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
        };
        /**
         * SenderType
         * @enum {string}
         */
        SenderType: SenderType;
        /** SupportLineOut */
        SupportLineOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Expires In */
            expires_in: number;
        };
        /** UpdateRoleIn */
        UpdateRoleIn: {
            /** @default buyer */
            role: components["schemas"]["Role"];
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Login */
            login: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["Role"];
            /** Support Line Id */
            support_line_id?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaActorOut = components['schemas']['ActorOut'];
export type SchemaAdminRatingOut = components['schemas']['AdminRatingOut'];
export type SchemaChatOut = components['schemas']['ChatOut'];
export type SchemaChatPage = components['schemas']['ChatPage'];
export type SchemaCloseIn = components['schemas']['CloseIn'];
export type SchemaCompanyProfileOut = components['schemas']['CompanyProfileOut'];
export type SchemaContractCreateIn = components['schemas']['ContractCreateIn'];
export type SchemaContractOut = components['schemas']['ContractOut'];
export type SchemaContractPartiesOut = components['schemas']['ContractPartiesOut'];
export type SchemaDocumentCreateIn = components['schemas']['DocumentCreateIn'];
export type SchemaDocumentOut = components['schemas']['DocumentOut'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaLoginIn = components['schemas']['LoginIn'];
export type SchemaMessageIn = components['schemas']['MessageIn'];
export type SchemaMessageOut = components['schemas']['MessageOut'];
export type SchemaMessagePage = components['schemas']['MessagePage'];
export type SchemaOfferCreateIn = components['schemas']['OfferCreateIn'];
export type SchemaOfferOut = components['schemas']['OfferOut'];
export type SchemaPartyOut = components['schemas']['PartyOut'];
export type SchemaProcurementCreateIn = components['schemas']['ProcurementCreateIn'];
export type SchemaProcurementOut = components['schemas']['ProcurementOut'];
export type SchemaProfileViewOut = components['schemas']['ProfileViewOut'];
export type SchemaRatingIn = components['schemas']['RatingIn'];
export type SchemaRatingOut = components['schemas']['RatingOut'];
export type SchemaRatingPage = components['schemas']['RatingPage'];
export type SchemaRecipientOut = components['schemas']['RecipientOut'];
export type SchemaRegisterIn = components['schemas']['RegisterIn'];
export type SchemaRequestOperatorIn = components['schemas']['RequestOperatorIn'];
export type SchemaSendResult = components['schemas']['SendResult'];
export type SchemaSupportLineOut = components['schemas']['SupportLineOut'];
export type SchemaTokenOut = components['schemas']['TokenOut'];
export type SchemaUpdateRoleIn = components['schemas']['UpdateRoleIn'];
export type SchemaUserOut = components['schemas']['UserOut'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    ping_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    get_my_profile_profile_get: {
        parameters: {
            query?: {
                /** @description Переопределить роль: seller (поставщик) или buyer (заказчик) */
                role?: components["schemas"]["Role"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sample_profile_profile_sample_get: {
        parameters: {
            query?: {
                /** @description Роль профиля: seller (поставщик) или buyer (заказчик) */
                role?: components["schemas"]["Role"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_role_profile_role_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_new_procurement_profile_procurements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcurementCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcurementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_new_offer_profile_offers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_offer_for_procurement_profile_procurements__procurement_id__offers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                procurement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_new_contract_profile_contracts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_new_document_profile_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_profile_contracts__contract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_support_lines_support_lines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportLineOut"][];
                };
            };
        };
    };
    list_chats_chats_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ChatStatus"] | null;
                topic?: string | null;
                subtopic?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_chat_chats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatOut"];
                };
            };
        };
    };
    get_chat_chats__chat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_chats__chat_id__messages_get: {
        parameters: {
            query?: {
                after_sequence?: number;
                limit?: number;
            };
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_chats__chat_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_message_chats__chat_id__stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_message_chats__chat_id__message_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_operator_chats__chat_id__request_operator_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestOperatorIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_chats__chat_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rate_chat_chats__chat_id__rating_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    support_chats_support_chats_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ChatStatus"] | null;
                topic?: string | null;
                subtopic?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_support_chats__chat_id__claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chats_admin_chats_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                status?: components["schemas"]["ChatStatus"] | null;
                line_id?: number | null;
                operator_id?: string | null;
                user_id?: string | null;
                topic?: string | null;
                subtopic?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ratings_admin_ratings_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                stars?: number | null;
                stars_lte?: number | null;
                sender_type?: components["schemas"]["SenderType"] | null;
                line_id?: number | null;
                operator_id?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_admin_stats_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_health_admin_ai_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    proxy_image_ml_assets_image__slug___filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_manuals_ml_api_knowledge_base_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_manual_structure_ml_api_knowledge_base__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manual_section_ml_api_knowledge_base__slug___section_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                section_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manul_manul_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
export enum ChatStatus {
    ai = "ai",
    waiting_operator = "waiting_operator",
    operator = "operator",
    closed = "closed"
}
export enum CloseInReason {
    resolved = "resolved",
    user_cancelled = "user_cancelled"
}
export enum CloseReason {
    resolved = "resolved",
    user_cancelled = "user_cancelled",
    moderation = "moderation"
}
export enum DocumentCreateInCategory {
    procurement = "procurement",
    contract = "contract",
    offer = "offer",
    company = "company"
}
export enum PartyOutRole {
    customer = "customer",
    supplier = "supplier"
}
export enum RecipientOutKind {
    ai = "ai",
    support_queue = "support_queue",
    operator = "operator",
    none = "none"
}
export enum Role {
    seller = "seller",
    buyer = "buyer",
    support = "support",
    admin = "admin"
}
export enum SenderType {
    user = "user",
    ai = "ai",
    operator = "operator",
    support = "support",
    system = "system"
}
